config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  get '/dashboard', to: "pages#dashboard"
  get '/planning', to: "pages#planning"
  resources :fighters do
    resources :events, only: %i[new create]
  end

  resources :fighter_weekly_availabilities, only: %i[update]
  resources :fighters_availabilities, only: %i[update]

  resources :events, only: %i[index show edit update destroy] do
    resources :reviews, only: %i[create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/fighter.rb
class Fighter < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_all_names,
                  against: %i[first_name last_name nickname],
                  using: {
                    tsearch: { prefix: true }
                  }

  belongs_to :user
  has_many :events, dependent: :nullify
  has_many :reviews, through: :events
  has_one :fighter_weekly_availability, dependent: :destroy
  has_many :fighters_availabilities, dependent: :destroy
  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  after_save :create_fighter_weekly_availability, if: :saved_change_to_id?

  validates :first_name, :last_name, :nickname, presence: true, length: { minimum: 1 }
  validates :nickname, uniqueness: true

  validates :birth_date, presence: true
  validate :validate_birth_date

  validates :height, presence: true, numericality: {
    greater_than_or_equal_to: 120,
    less_than_or_equal_to: 300,
    message: "must be between 120 and 300 cm"
  }
  validates :weight, presence: true, numericality: {
    greater_than_or_equal_to: 45,
    less_than_or_equal_to: 200,
    message: "must be between 45 and 200 kg"
  }
  validate :validate_description

  # Calculate average rating for the fighter
  def average_rating
    return 0 if reviews.empty? || reviews.where(user_to_fighter: true).empty?

    reviews.where(user_to_fighter: true).average(:rating).round(1) # Adjust the rounding as needed
  end

  # Count the number of reviews for the fighter
  def reviews_count
    reviews.where(user_to_fighter: true).count
  end

  def accepted_passed_events
    events.where(status: "accepted").where("start_time < ?", Time.current).count
  end

  def rounded_price
    price.round
  end
  # def self.generate_arriving_disponibility
  # end

  private

  def validate_description
    validate_field_cannot_have_only_whitespace(:description)
  end

  def validate_birth_date
    date_cannot_be_too_late(:birth_date,
                            message: "can't be in the future")
    date_cannot_be_too_late(:birth_date,
                            ante_quem: Date.today - 14.years,
                            message: "can't be less than 14 years old")
    date_cannot_be_too_early(:birth_date,
                             post_quem: Date.today - 120.years,
                             message: "can't be more than 120 years old")
  end

  def create_fighter_weekly_availability
    FighterWeeklyAvailability.create!(fighter: self)
  end
end

app/controllers/fighters_controller.rb
class FightersController < ApplicationController
  before_action :set_fighter_by_user_id, only: %i[edit destroy]
  before_action :set_fighter, only: %i[show update]

  def index
    @fighters = Fighter.all
    @markers = @fighters.geocoded.map do |fighter|
      {
        lat: fighter.latitude,
        lng: fighter.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { fighter: fighter })
      }
    end
    @duration = params[:duration].present? && !params[:duration].empty? ? params[:duration].to_i : 1
    @fighters = @fighters.search_by_all_names(params[:name]) if params[:name].present? && !params[:name].empty?
    return unless params[:date].present?

    @fighters = @fighters
                .joins(:fighters_availabilities)
                .where(fighters_availabilities: { is_available: true })
                .where("DATE(fighters_availabilities.start_time) = ?", params[:date])
  end

  def show
    @event = Event.new
    @fighter = Fighter.find(params[:id])
    # puts @fighter
    @markers = [
      {
        lat: @fighter.latitude,
        lng: @fighter.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { fighter: @fighter })
      }
    ]
  end

  def new
    @fighter = Fighter.new
  end

  def create
    @fighter = Fighter.new(fighter_params)
    @fighter.user = current_user
    if @fighter.save
      # dashboard_path is a placeholder, waiting for fighter's profile (route by pages)
      redirect_to fighter_path(@fighter), notice: "Congradulation! You just created your fighter's profile."
    else
      redirect_to new_fighter_path, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @fighter.update(fighter_params)
      redirect_to dashboard_path, notice: "Your fighter's profile is updated." # :accepted
    else
      redirect_to edit_fighter_path, status: 422
    end
  end

  def destroy
    if @fighter.destroy
      redirect_to dashboard_path, warning: "Your fighter's profile is deleted."
    else
      redirect_to dashboard_path, status: 422, warning: "Oups you cannot stop fighting!"
    end
  end

  private

  def set_fighter_by_user_id
    @fighter = Fighter.find_by(user_id: params[:id])
  end

  def set_fighter
    @fighter = Fighter.find(params[:id])
  end

  def fighter_params
    params.require(:fighter).permit(
      :user_id,
      :first_name, :last_name, :nickname, :birth_date,
      :height, :weight, :fight_style, :description,
      :price, :have_insurance,
      :photo,
      :address
    )
  end
end

app/views/fighters/_form.html.erb
<%= simple_form_for(fighter) do |f| %>
  <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
  <%= f.input :first_name, input_html: {value: current_user.fighter ? fighter.first_name : current_user.first_name} %>
  <%= f.input :last_name, input_html: {value: current_user.fighter ? fighter.last_name : current_user.last_name} %>
  <%= f.input :nickname %>
  <%= f.input :price, label: "Price (€ / HT)", input_html: { value: fighter.price ? fighter.price : 100.0 } %>
  <%= f.input :birth_date, as: :date, html5: true %>
  <%= f.input :height, label: "Height (cm)" %>
  <%= f.input :weight, label: "Weight (kg)" %>
  <%= f.input :fight_style %>
  <%= f.input :description, placeholder: "Wraaak..." %>
  <%= f.input :address, placeholder: "Your address" %>
  <%= f.input :have_insurance, label: "I have insurance" %>
  <div class="form-actions">
    <div class="row justify-content-around pb-3">
      <div class="col-md-5">
        <%= f.button :submit, label: btn_text,
                      class:"btn btn-danger text-light me-3",
                      style:"width:100%" %>
      </div>
      <div class="col-md-5">
        <% if action_name == "new" %>
          <%= link_to "Go Back", dashboard_path,
                      class:"btn btn-secondary",
                      style:"width:100%" %>
        <% else %>
          <%= link_to "Delete Fighter\'s profile", fighter_path(current_user),
                      data: {turbo_method: :delete, turbo_confirm: "sure ?"},
                      class:"btn btn-outline-secondary" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/fighters/_index.html.erb
<div class="container-fluid mb-5">
  <div class="row">
    <div class="col-lg-9">
      <div class="fighters-header d-flex align-items-center justify-content-between mb-3">
        <%= render "fighters/search_bar" %>
      </div>

      <div class="fighters-list">
        <% fighters.each do |fighter| %>
          <div class="col-lg-4 col-md-6">
            <%= link_to fighter_path(fighter), class: "text-decoration-none text-dark" do %>
              <div class="h-100 fighter-card">
                <div class="fighter-image position-relative">
                  <%= render "shared/default_photo",
                    item: fighter,
                    path: ["https://partyanimals.com/media/avatars/thumbnails/avatars-", ".webp"],
                    alt: "#{fighter.nickname}'s image",
                    class_name: "card-img-top rounded fighter-img p-1", alt: "#{fighter.nickname}'s profile photo" %>
                  <div class="fighter-height position-absolute">
                    <p class="stat mb-0"><%= "#{fighter.height}cm" %></p>
                  </div>
                  <div class="fighter-weight position-absolute">
                    <p class="stat mb-0"><%= "#{fighter.weight}kg" %></p>
                  </div>
                </div>
                <div class="card-body d-flex flex-column p-3">
                  <div class="d-flex justify-content-between align-items-center mb-2">
                    <h5 class="card-title mb-0"><%= "#{fighter.nickname}" %></h5>
                    <div class="rating">
                      <span><i class="fa-solid fa-star"></i></span>
                      <span><%= fighter.average_rating %></span>
                      <span>(<%= fighter.reviews_count %>)</span>
                    </div>
                  </div>
                  <p class="card-subtitle text-muted mb-2"><%= "#{fighter.fight_style}" %></p>
                  <p class="card-text text-muted"><%= truncate(fighter.description, length: 50) %></p>
                  <div class="bottom-card d-flex justify-content-between align-items-baseline mt-auto">
                    <p class="price-pill rounded-pill px-3 py-1"><%="💰 #{fighter.rounded_price}€/h" %></p>
                    <p class="total text-end text-muted small mb-0"><%= "#{fighter.rounded_price * @duration}€ au total" %></p>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-lg-3 p-0">
      <div class="map-container">
        <div class="map-content">
          <div style="width: 100%; height: 100%;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/fighters/_info_window.html.erb
<h2><%= fighter.nickname %></h2>
<p><%= fighter.address %></p>
<%= link_to "book this fighter", fighter_path(fighter) %>

app/views/fighters/_search_bar.html.erb
<%= form_with url: fighters_path, method: :get, html: {class: "row", style:"width:100%"} do %>
  <div class="col-xl-3">
    <%= text_field_tag :name,
    params[:name],
    class: "form-control",
    placeholder: "Find your fighter..." %>
  </div>

  <div class="col-xl-3">
    <%= date_field_tag :date,
    params[:date],
    class: "form-control",
    value: Date.today,
    min: Date.today,
    max: 14.days.from_now.to_date %>
  </div>

  <div class="col-xl-3">
    <div class="input-group">
      <%= number_field_tag :duration,
      params[:duration],
      min: 1, max: 6,
      placeholder: 1,
      class: "form-control" %>
      <div class="input-group-append">
        <span class="input-group-text">hours</span>
      </div>
    </div>
  </div>

  <div class="col-xl-3">
    <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/fighters/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-xl-6 col-md-10">

      <%= render "fighters/form", btn_text: "Update Fighting Profile", fighter: @fighter %>
      <%= link_to "Back to Profile Page", dashboard_path %>

    </div>
  </div>
</div>

app/views/fighters/index.html.erb
<div class="container ms-3">
<h1>Let's Hit!</h1>

<%# With all fighter's cards %>
<%= render "fighters/index", fighters: @fighters %>
</div>

app/views/fighters/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-xl-6 col-md-10">
      <h2>Become Fighter!</h2>
      <%= render "fighters/form", btn_text: "I WANT TO FIGHT", fighter: @fighter %>
    </div>
  </div>
</div>

app/views/fighters/show.html.erb
<div class="main-container ms-5 me-5">
  <h2 class="py-3 ms-5"><%= "#{@fighter.nickname}" %></h2>
  <div class="d-flex justify-content-center">
    <div class="col-lg-6">
      <div class="fighter-infos">
        <div class="d-flex fighter-photos">
          <div class="col-8">
          <%= render "shared/default_photo",
            item: @fighter,
            path: ["https://partyanimals.com/media/avatars/thumbnails/avatars-", ".webp"],
            alt: "#{@fighter.nickname}'s image",
            class_name: "card-img-top rounded fighter-img p-1", alt: "#{@fighter.nickname}'s profile photo" %>
          </div>
          <div class="col-4">
            <img src="https://partyanimals.com/media/avatars/thumbnails/avatars-12.webp" alt="img fighter" width=97% class="mb-3">
            <img src="https://partyanimals.com/media/avatars/thumbnails/avatars-16.webp" alt="img fighter" width=97%>
          </div>
        </div>
      </div>
      <div class="fighter-details mt-3">
        <h3><%= "#{@fighter.first_name} #{@fighter.last_name}" %></h3>
        <p><i class="fa-solid fa-ruler-vertical"></i><%= " #{@fighter.height}cm  |  "%>
          <i class="fa-solid fa-weight-scale"></i></i><%= " #{@fighter.weight} kg " %></p>
        <p><i class="fa-solid fa-user-ninja"></i><%= " Fight style:"%>
          <b><%="#{@fighter.fight_style}" %></b>
        </p>
        <hr class="mt-4">
        <div class="avatar-section">
          <%= render "shared/default_photo", item: @fighter, path: ["https://partyanimals.com/media/avatars/thumbnails/avatars-", ".webp"], class_name: "avatar", alt: "avatar" %>
          <div class="notification-content">
            <h5>Fighter experience</h5>
            <p>I have completed <b><%= @fighter.accepted_passed_events %></b> fight <%= @fighter.accepted_passed_events > 1 ? "s" : "" %></p>
          </div>
        </div>
        <div>
          <hr>
          <h4>Description</h4>
          <p><%="#{@fighter.description}" %></p>
        </div>
      </div>
    </div>
    <div class="form ms-3 col-lg-5">
      <%= render "events/form", fighter: @fighter, event: @event %>
    </div>
  </div>
  <div class="reviews-container col-lg-12 mx-5">
    <div class="row">
      <hr>
      <h4>Reviews</h4>
      <% @fighter.reviews.each do |review| %>
          <% if review.user_to_fighter %>
      <div class="col-lg-6">
            <%= render "reviews/show", review: review %>
      </div>
          <% end %>
        <% end %>
    </div>
  </div>

  <div class="map mx-5">
    <hr>
    <h4>Where to find me?</h4>
    <div class="row">
      <div class="fighter-map-container">
        <div class="fighter-map-content">
          <div style="width: 100%; height: 400px;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>
</div>




  <%# <div class="card">
    <% unless current_user && current_user.fighter && current_user.fighter.id == @fighter.id %>
      <%# <%= link_to "> book an event with #{@fighter.nickname}", new_fighter_event_path(@fighter), class:"btn btn-danger text-light" %>
    <%# <% end %>
  <%# </div> %>