config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  get '/dashboard', to: "pages#dashboard"
  get '/planning', to: "pages#planning"
  resources :fighters do
    resources :events, only: %i[new create]
  end

  resources :fighter_weekly_availabilities, only: %i[update]
  resources :fighters_availabilities, only: %i[update]

  resources :events, only: %i[index show edit update destroy] do
    resources :reviews, only: %i[create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_anonyme_name.html.erb
<%# <%= render "shared/anonyme_name", user: user_instance/fighter_instance %>
<% first = user.first_name[0] + "*" * 3 %>

<% if user.last_name.length > 4 %>
  <% last = user.last_name[0..1] + "*" * (user.last_name.length - 3) + user.last_name[-1] %>
<% else %>
  <% last = user.last_name[0] + "*" * 3  %>
<% end %>



<%= "#{first} #{last}" %>

app/views/shared/_default_photo.html.erb
<%# accept variables:
  item,
  path/ (for img's path),
  class_name (empty string if no specific class),
  alt %>
<% style = style || "" %>
<% class_name = class_name || "" %>
<% default_img = default_img || "" %>
<% if !default_img.empty? %>
    <%= image_tag default_img, class: class_name, alt: alt, style: style %>
<% elsif item.image_path %>
    <%= image_tag "#{path[0]}#{item.image_path}#{path[1]}", class: class_name, alt: alt, style: style %>
<% else %>
  <%= image_tag "#{path[0]}9#{path[1]}", class: class_name, alt: alt, style: style %>
<% end %>

app/views/shared/_fighter_name.html.erb
<%# <%= render "shared/fighter_name", fighter: fighter_instance %>
<%= "#{fighter.first_name} #{fighter.last_name} \"#{fighter.nickname}\"" %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="bg-dark footer">
  <p class="text-light text-center m-0">
  © 2024 Groupe Skill Match. Tous droits réservés.
  </p>
</div>

app/views/shared/_medal.html.erb
<%# res : a number between 0 and 1  %>
<%# Example : <%= render "shared/medal", class_name: "fs-3", res: (current_user.fighter.average_rating / 5) %>
<% if res > 0.6 %>
  <% color = "#FFD700" %>
<% elsif res > 0.2 %>
  <% color = "#C0C0C0" %>
<% else %>
  <% color = "#CD7F32" %>
<% end %>
<i class="fa-solid fa-medal <%= "#{class_name}" %>" style="color:<%= color %>"></i>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon bg-light" data-bs-theme="light">
  <div class="container-fluid px-4">
    <%= link_to root_path do %>
      <%= image_tag "logo_1200x800.png", style: "height:80px" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Events", events_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= render "shared/default_photo", item: current_user, default_img: "https://partyanimals.com/media/avatars/avatars-2.png", class_name: "avatar", alt: "avatar" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My profile", dashboard_path, class: "dropdown-item" %>
              <% if current_user.fighter %>
                <%= link_to "My planning", planning_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to "Historical records", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Events", events_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_user_name.html.erb
<%# <%= render "shared/user_name", user: user_instance %>
<%= "#{user.first_name} #{user.last_name}" %>