config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  get '/dashboard', to: "pages#dashboard"
  get '/planning', to: "pages#planning"
  resources :fighters do
    resources :events, only: %i[new create]
  end

  resources :fighter_weekly_availabilities, only: %i[update]
  resources :fighters_availabilities, only: %i[update]

  resources :events, only: %i[index show edit update destroy] do
    resources :reviews, only: %i[create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/pages/_info_window.html.erb
<h2><%= fighter.nickname %></h2>
<p><%= fighter.address %></p>

app/views/pages/dashboard.html.erb
<div class="container">
  <h1 class="d-flex justify-content-between">
  Hello, <%= current_user.first_name ? current_user.first_name : current_user.email %>!
    <span>
    <%# ----- start of the edit profile button group ----- %>
      <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
      <% unless current_user.fighter %>
        <%= link_to 'Edit Profile', edit_user_registration_path, class:"btn btn-danger text-light" %>
        <%= link_to 'Become Fighter', new_fighter_path, class:"btn btn-dark"  %>
      <% else %>
        <div class="btn-group" role="group">
          <button type="button" class="btn btn-secondary rounded-pill"
          data-bs-toggle="dropdown" aria-expanded="false">
            Edit Profile
          </button>
          <ul class="dropdown-menu">
            <li>
                <%= link_to 'Edit USER Profile', edit_user_registration_path, class:"dropdown-item" %>
            </li>
            <li>
                <%= link_to 'Edit FIGHTER Profile', edit_fighter_path(current_user), class:"dropdown-item" %>
            </li>
          </ul>
        </div>
      <% end %>
      </div>
    <%# ----- end of the edit profile button group ----- %>
    </span>

  </h1>
<hr class="hr-short">

<%= render "events/personal_index", events: @events, fighter_events: @fighter_events %>



</div>

app/views/pages/historical_records.html.erb
    <% if fighter_events[1] %>
      <h3>Your coming events!</h3>
      <% fighter_events[1].each do |event| %>
        <div class="col-xl-4 col-md-6 my-1">
          <div class="card" style="height:100%">
            <%= render "shared/default_photo",
                        item: event,
                        default_img: img_paths.sample,
                        class_name: "",
                        alt: "#{event.title}'s image" %>
            <div class="card-body">
              <h5 class="card-title">
                <%= event.title %>
                <%= render "events/status_badge", status: event.status, date: event.end_time %>

              </h5>
              <p class="card-text">
                <%= event&.place %>
              </p>
              <%= link_to "See more", event_path(event), class:"badge text-bg-primary text-light link-offset-2 link-underline link-underline-opacity-0" %>
                            <%= button_to "Pending the invitation",
                          event_path(event, event: { status: "pending"}),
                          method: :patch,
                          class: "border border-0 badge text-bg-success text-light link-offset-2 link-underline link-underline-opacity-0" %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>

app/views/pages/home.html.erb
<div class="container ms-5">
<h1>Let's Hit!</h1>

<%# With all fighter's cards %>
<%= render "fighters/index", fighters: @fighters %>
</div>

app/views/pages/planning.html.erb
<div class="container">
  <div class="d-flex justify-content-between">
    <span class="fs-1">
      Hello, Fighter <%= current_user.fighter.nickname.capitalize %>!
      <%= render "shared/medal", class_name: "fs-1", res: (current_user.fighter.average_rating/5) %>
    </span>
    <span>
      <%= link_to 'Edit FIGHTER Profile', edit_fighter_path(current_user), class:"btn btn-secondary rounded-pill" %>
    </span>
  </div>

  <hr class="hr-short">

  <h2 class="mb-3">My events and availability for 14 coming days</h2>
  <div style="display:grid;grid-template-columns: repeat(7, 1fr)">
  <% [0..6, 7..13].each do |scope| %>
    <% @real_days[scope].each do |day| %>
      <div class="card text-bg-light mb-3">
        <div class="card-header text-center">
          <%= day.strftime("%a %d %b") %>
        </div>
        <div class="card-body">
          <% slot = @availabilities.find_by("DATE(start_time) = ?", day) %>
          <% reservation = @reservations.find_by("DATE(start_time) = ?", day) %>
          <% if slot %>
            <% if reservation %>
              <%= link_to event_path(reservation), class:"align-middle text-start all-inherit" do %>
                <div class="card rounded">
                  <div class="card-body p-2" style="font-size:0.75rem">
                    At <%= reservation.start_time.hour %>:00 | <%= reservation.title %>
                    <br>
                    <span class="text-body-secondary">
                    booked by: <%= reservation.user.first_name %>
                    </span>
                  </div>
                </div>
              <% end %>
            <% else %>
              <%= button_to fighters_availability_path(slot, fighters_availability: { is_available: !slot.is_available }),
                            method: :patch,
                            form: {style: 'margin-top: 0;'},
                            class: slot.is_available ? "border border-0 badge text-bg-success text-light link-offset-2 link-underline link-underline-opacity-0" : "border border-0 badge text-bg-secondary text-light link-offset-2 link-underline link-underline-opacity-0" do %>
              <%= slot.is_available ? "Available" : "Unavailable" %>
            <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
  </div>
  <h2>My weekly schedule</h2>

<table class="table table-striped-columns text-center">
  <thead>
    <tr>
      <% @days_of_week.each do |day| %>
        <th scope="col"><%= day[0..2].capitalize %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>


  <%= simple_form_for @availability do |f|%>
    <tr>
      <% @days_of_week.each do |day| %>
        <td>
          <%= f.input day.to_sym, as: :boolean, label: false,
          input_html: {
            style: "width: 1.5em; height: 1.5em; margin: auto",
            class: "border border-2",
          },
            wrapper: false
          %>
        </td>
      <% end %>
    </tr>

  </tbody>
</table>
    <%= f.button :submit, "Save my change", class: "btn btn-primary" %>
  <% end %>



</div>